# Generated by Django 3.2.6 on 2022-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221217_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_subscribed',
            field=models.BooleanField(default=False, help_text='Отметьте для подписки на данного пользователя', verbose_name='Подписка на данного пользователя'),
        ),
    ]
